'use strict';
const C={URLS:{GEM_BIDS:'https://bidplus.gem.gov.in/all-bids',TOT_SEARCH:'https://www.tendersontime.com/tenders/',T247_BASE:'https://www.tender247.com/keyword/'},MSG:{INJECT_SCRAPE:'INJECT_SCRAPE',PAGE_READY:'PAGE_READY',CAPTCHA_DETECTED:'CAPTCHA_DETECTED',CAPTCHA_SOLVED:'CAPTCHA_SOLVED',DATA_EXTRACTED:'DATA_EXTRACTED',NAVIGATION_DONE:'NAVIGATION_DONE',STREAM_TENDER:'STREAM_TENDER',STREAM_LOG:'STREAM_LOG',STREAM_PROGRESS:'STREAM_PROGRESS',SCRAPE_COMPLETE:'SCRAPE_COMPLETE',STATUS_UPDATE:'STATUS_UPDATE',START_SCRAPE:'START_SCRAPE',STOP_SCRAPE:'STOP_SCRAPE',GET_STATUS:'GET_STATUS',GET_EXTENSION_ID:'GET_EXTENSION_ID'}};
const state={jobs:new Map(),ports:new Set(),tabJobs:new Map(),jobTabs:new Map(),running:new Set(),paused:false,seenIds:new Set()};
chrome.alarms.create('ka',{periodInMinutes:0.4});
chrome.alarms.onAlarm.addListener(function(){chrome.storage.local.set({_ka:Date.now()});});
setInterval(function(){chrome.storage.local.set({_sw:Date.now()});},20000);
chrome.runtime.onConnectExternal.addListener(function(port){if(port.name!=='gem-dashboard'&&port.name!=='gem-scraper')return;state.ports.add(port);broadcast({type:C.MSG.STATUS_UPDATE,payload:buildStatus()});port.onMessage.addListener(function(msg){handleDashboard(msg,port);});port.onDisconnect.addListener(function(){state.ports.delete(port);});});
chrome.runtime.onMessageExternal.addListener(function(msg,_s,sr){if(msg.type===C.MSG.GET_EXTENSION_ID)sr({extensionId:chrome.runtime.id,version:'3.0.0'});if(msg.type===C.MSG.GET_STATUS)sr(buildStatus());return true;});
chrome.runtime.onMessage.addListener(function(msg,sender,sr){var tabId=sender.tab?sender.tab.id:null;if(!tabId)return;if(msg.type==='SAVE_CREDENTIALS'){var o={};o['creds_'+msg.payload.portal]={username:msg.payload.username,password:msg.payload.password};chrome.storage.local.set(o,function(){sr({saved:true});});return true;}if(msg.type==='GET_CREDENTIALS'){var k='creds_'+msg.payload.portal;chrome.storage.local.get(k,function(d){sr({creds:d[k]||null});});return true;}if(msg.type==='CLEAR_CREDENTIALS'){chrome.storage.local.remove('creds_'+msg.payload.portal,function(){sr({cleared:true});});return true;}if(msg.type==='STREAM_LOG'){broadcast({type:C.MSG.STREAM_LOG,payload:msg.payload});sr({ack:true});return true;}var jobId=state.tabJobs.get(tabId);if(!jobId){if(msg.type===C.MSG.DATA_EXTRACTED){var tenders=(msg.payload&&msg.payload.tenders)||[];var fresh=tenders.filter(function(t){return t&&t.bidId&&!state.seenIds.has(t.bidId);});fresh.forEach(function(t){state.seenIds.add(t.bidId);broadcast({type:C.MSG.STREAM_TENDER,payload:t});});if(fresh.length>0)broadcast({type:C.MSG.STREAM_PROGRESS,payload:{jobId:'recovered',message:'Received '+fresh.length+' tenders',progress:90,status:'SCRAPING',totalFound:fresh.length,downloaded:0,failed:0}});sr({received:fresh.length});}else if(msg.type===C.MSG.NAVIGATION_DONE){var tot=(msg.payload&&msg.payload.totalExtracted)||0;broadcast({type:C.MSG.SCRAPE_COMPLETE,payload:{jobId:'recovered',totalFound:tot,downloaded:0,failed:0,duration:0}});sr({ack:true});}else if(msg.type===C.MSG.CAPTCHA_DETECTED){state.paused=true;sr({waiting:true});}else if(msg.type===C.MSG.CAPTCHA_SOLVED){state.paused=false;sr({resume:true});}else{sr({ack:true});}return true;}handleContent(msg,tabId,jobId,sr);return true;});
chrome.tabs.onUpdated.addListener(function(tabId,changeInfo){if(changeInfo.status!=='complete')return;var jobId=state.tabJobs.get(tabId);if(!jobId)return;var job=state.jobs.get(jobId);if(!job)return;if(job.status==='NAVIGATING'){updateJob(jobId,{status:'SCRAPING'});setTimeout(function(){injectScrape(tabId,jobId);},1500);}else if(job.status==='CAPTCHA_WAIT'||job.status==='SCRAPING'){state.paused=false;}});
chrome.tabs.onRemoved.addListener(function(tabId){var jobId=state.tabJobs.get(tabId);if(jobId){state.tabJobs.delete(tabId);state.jobTabs.delete(jobId);}});
function enqueueJob(c){var id='job_'+Date.now();var j={id:id,portal:c.portal||'gem',categories:c.categories||[],keywords:c.keywords||[],fromDate:c.fromDate||'',toDate:c.toDate||'',status:'QUEUED',progress:0,totalFound:0,downloaded:0,failed:0,retries:0,startedAt:null,createdAt:Date.now()};state.jobs.set(id,j);drainQueue();return id;}
function drainQueue(){if(state.paused)return;var q=[];state.jobs.forEach(function(j){if(j.status==='QUEUED')q.push(j);});q.sort(function(a,b){return a.createdAt-b.createdAt;});q.forEach(function(j){if(state.running.size<2)startJob(j.id);});}
function startJob(jobId){var job=state.jobs.get(jobId);if(!job)return;state.running.add(jobId);updateJob(jobId,{status:'NAVIGATING',startedAt:Date.now()});var url;if(job.portal==='gem'){url=C.URLS.GEM_BIDS;}else if(job.portal==='tendersontime'){url=C.URLS.TOT_SEARCH;}else{var kw=(job.keywords[0]||'').trim().replace(/\s+/g,'+');url=C.URLS.T247_BASE+(kw?kw+'+tenders':'tenders');}chrome.tabs.create({url:url,active:false},function(tab){if(chrome.runtime.lastError){failJob(jobId,chrome.runtime.lastError.message);return;}state.tabJobs.set(tab.id,jobId);state.jobTabs.set(jobId,tab.id);broadcastProgress(jobId,'Opening '+url,5);});}
function completeJob(jobId){var job=state.jobs.get(jobId);if(!job)return;updateJob(jobId,{status:'DONE',progress:100});state.running.delete(jobId);broadcast({type:C.MSG.SCRAPE_COMPLETE,payload:{jobId:jobId,totalFound:job.totalFound,downloaded:0,failed:0,duration:Math.round((Date.now()-job.startedAt)/1000)}});var tabId=state.jobTabs.get(jobId);if(tabId){chrome.tabs.remove(tabId,function(){});state.tabJobs.delete(tabId);state.jobTabs.delete(jobId);}drainQueue();}
function failJob(jobId,reason){var job=state.jobs.get(jobId);if(!job)return;if(job.retries<3){updateJob(jobId,{status:'QUEUED',retries:job.retries+1});state.running.delete(jobId);setTimeout(drainQueue,3000);}else{updateJob(jobId,{status:'FAILED'});state.running.delete(jobId);drainQueue();}}
function injectScrape(tabId,jobId){var job=state.jobs.get(jobId);if(!job)return;setTimeout(function(){chrome.tabs.sendMessage(tabId,{type:C.MSG.INJECT_SCRAPE,payload:{portal:job.portal,categories:job.categories,keywords:job.keywords,fromDate:job.fromDate,toDate:job.toDate,jobId:jobId}},function(){if(chrome.runtime.lastError){setTimeout(function(){chrome.tabs.sendMessage(tabId,{type:C.MSG.INJECT_SCRAPE,payload:{portal:job.portal,categories:job.categories,keywords:job.keywords,jobId:jobId}},function(){});},2000);}});},1200);}
function handleContent(msg,tabId,jobId,sr){var job=state.jobs.get(jobId);if(!job){sr({noJob:true});return;}if(msg.type===C.MSG.PAGE_READY){if(job.status==='NAVIGATING'){updateJob(jobId,{status:'SCRAPING'});injectScrape(tabId,jobId);}sr({ack:true});}else if(msg.type===C.MSG.CAPTCHA_DETECTED){state.paused=true;updateJob(jobId,{status:'CAPTCHA_WAIT'});chrome.tabs.update(tabId,{active:true},function(){});sr({waiting:true});}else if(msg.type===C.MSG.CAPTCHA_SOLVED){state.paused=false;updateJob(jobId,{status:'SCRAPING'});sr({resume:true});}else if(msg.type===C.MSG.DATA_EXTRACTED){var tenders=(msg.payload&&msg.payload.tenders)||[];var fresh=tenders.filter(function(t){return t&&t.bidId&&!state.seenIds.has(t.bidId);});fresh.forEach(function(t){state.seenIds.add(t.bidId);});var nt=(job.totalFound||0)+fresh.length;var np=Math.min((job.progress||0)+10,88);updateJob(jobId,{totalFound:nt,progress:np});fresh.forEach(function(t){broadcast({type:C.MSG.STREAM_TENDER,payload:t});});broadcastProgress(jobId,nt+' tenders captured',np);sr({received:fresh.length});}else if(msg.type===C.MSG.NAVIGATION_DONE){var total=(msg.payload&&msg.payload.totalExtracted)||job.totalFound||0;broadcastProgress(jobId,'Done - '+total+' tenders',95);if(msg.payload&&msg.payload.allDone)setTimeout(function(){completeJob(jobId);},600);sr({ack:true});}else{sr({ack:true});}}
function handleDashboard(msg,port){if(msg.type===C.MSG.START_SCRAPE){var jobId=enqueueJob(msg.payload||{});port.postMessage({type:'JOB_CREATED',jobId:jobId});}else if(msg.type===C.MSG.STOP_SCRAPE){state.running.forEach(function(id){failJob(id,'Stopped');});port.postMessage({type:'ALL_STOPPED'});}else if(msg.type===C.MSG.GET_STATUS){port.postMessage({type:'STATUS_UPDATE',payload:buildStatus()});}}
function broadcast(msg){state.